package com.phegondev.InventoryMgtSystem.enums;

public enum QuyenTacVu {
    SAN_PHAM_CREATE,
    SAN_PHAM_READ,
    SAN_PHAM_UPDATE,
    SAN_PHAM_DELETE,

    DANH_MUC_CREATE,
    DANH_MUC_READ,
    DANH_MUC_UPDATE,
    DANH_MUC_DELETE,

    NHA_CUNG_CAP_CREATE,
    NHA_CUNG_CAP_READ,
    NHA_CUNG_CAP_UPDATE,
    NHA_CUNG_CAP_DELETE,

    KHACH_HANG_CREATE,
    KHACH_HANG_READ,
    KHACH_HANG_UPDATE,
    KHACH_HANG_DELETE,

    GIAO_DICH_CREATE,
    GIAO_DICH_READ,
    GIAO_DICH_UPDATE,
    GIAO_DICH_DELETE,

    DON_BAN_HANG_CREATE,
    DON_BAN_HANG_READ,
    DON_BAN_HANG_UPDATE,
    DON_BAN_HANG_DELETE,

    DON_DAT_HANG_CREATE,
    DON_DAT_HANG_READ,
    DON_DAT_HANG_UPDATE,
    DON_DAT_HANG_DELETE,

    KHO_CREATE,
    KHO_READ,
    KHO_UPDATE,
    KHO_DELETE,

    KIEM_KE_CREATE,
    KIEM_KE_READ,
    KIEM_KE_UPDATE,
    KIEM_KE_DELETE,

    BAO_CAO_READ,
    DASHBOARD_READ,

    MA_VACH_READ,

    LO_HANG_CREATE,
    LO_HANG_READ,
    LO_HANG_UPDATE,
    LO_HANG_DELETE,

    EXCEL_EXPORT,
    EXCEL_IMPORT,
    PDF_EXPORT,

    USER_CREATE,
    USER_READ,
    USER_UPDATE,
    USER_DELETE,

    NHAT_KY_READ
}
